services:
    jt_file.uploader:
<<<<<<< HEAD
        class: JT\FileBundle\Uploader\FileUploader
        
    jt_file.deleter:
        class: JT\FileBundle\Uploader\FileDeleter

    jt_file.uploadable_file_listener:
        class: JT\FileBundle\EventListener
        arguments: ["@jt_file.uploader", "@jt_file.deleter"]
=======
        class: JT\FileBundle\Uploader;

	jt_file.uploadable_file_listener:
        class: JT\FileBundle\EventListener
        arguments: ["@jt_file.uploader"]
>>>>>>> ad591436b40a24ad124f92f9b9ce4ad77bf3920c


