services:
    jt_file.uploader:
        class: JT\FileBundle\Uploader\FileUploader
        arguments: ["@filesystem", "%kernel.root_dir%"]
        
    jt_file.downloader:
        class: JT\FileBundle\Uploader\FileDownloader
        arguments: ["@filesystem", "%kernel.root_dir%"]

    jt_file.uploadable_file_listener:
        class: JT\FileBundle\EventListener\FileToUploadListener
        arguments: ["@jt_file.uploader"]
        tags:
            - { name: doctrine.event_subscriber }
