<?php

namespace TaskBundle\Repository;

use UserBundle\Entity\User;
use Doctrine\ORM\Query\Expr;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUser(User $user)
	{
		return $this
			->createQueryBuilder('t')
			->join('t.users', 'u', Expr\Join::WITH, 'u = :user')
			->setParameter('user', $user)
			->getQuery()
			->getResult()
		;
	}
}
