<?php

namespace AppBundle\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByNameLike($name)
	{
		return $this
			->createQueryBuilder('c')
			->where('c.name LIKE :name')
			->setParameter('name', "%$name%")
			->getQuery()
			->getResult()
		;
	}
}