<?php

namespace AppBundle\Repository;

use UserBundle\Entity\Team;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function createContactByTeamQueryBuilder(Team $team)
    {
        return $this->createQueryBuilder('c')
            ->where('c.team = :team')
            ->setParameter('team', $team)
        ;
    }
}
