jt_mail:
    resource: "@JTMailBundle/Resources/config/routing.yml"
    prefix:   /mail

jt_contact_us:
    resource: "@JTContactUsBundle/Resources/config/routing.yml"
    prefix:   /contact

maps:
    resource: "@MapsBundle/Controller/"
    type:     annotation
    prefix:   /

app_contact:
    resource: "@AppBundle/Controller/ContactController.php"
    type:     annotation

user_invitation:
    resource: "@UserBundle/Controller/InvitationController.php"
    type:     annotation

user_team:
    resource: "@UserBundle/Controller/TeamController.php"
    type:     annotation

task:
    resource: "@TaskBundle/Controller/"
    type:     annotation
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

google_login:
    path: /login/check-google

calendar:
    resource: "@CalendarBundle/Controller/"
    type:     annotation
    prefix:   /calendar

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options:
        expose: true

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"