<?php

namespace UserBundle\Repository;

use UserBundle\Entity\User;
use Doctrine\ORM\Query\Expr;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
	public function findMyteam(User $user)
	{
		/* Search the user's team in which he's a member */
		$result = $this
			->createQueryBuilder('t')
			->join('t.members', 'u', Expr\Join::WITH, 'u = :user')
			->setParameter('user', $user)
			->getQuery()
			->getOneOrNullResult()		
		;
		
		/* Search the user's team in which he's an admin */
		if ($result == null) {
			return $this
				->createQueryBuilder('t')
				->join('t.admins', 'a', Expr\Join::WITH, 'a = :user')
				->setParameter('user', $user)
				->getQuery()
				->getOneOrNullResult()		
			;
		}
		
		return $result;
	}
	
	public function findLike($search)
	{
		return $this
			->createQueryBuilder('t')
			->where('t.name LIKE :search')
			->setParameter('search', "%$search%")
			->getQuery()
			->getResult()
		;
	}
}
