<?php

namespace UserBundle\Repository;

use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function createAllMyTeamQueryBuilder(User $user)
	{
		$query = $this->createQueryBuilder('u');
		
		if ($user->getTeam() != null)
		{
			$query
				->where('u.team = :team')
				->orWhere('u.teamAdmin = :ateam')
				->setParameter('team', $user->getTeam())
				->setParameter('ateam', $user->getTeam())
			;
		}
		elseif ($user->getTeamAdmin() != null) {
			$query
				->where('u.team = :team')
				->orWhere('u.teamAdmin = :ateam')
				->setParameter('team', $user->getTeamAdmin())
				->setParameter('ateam', $user->getTeamAdmin())
			;
		} else {
			// No team => Only the user
			$query
				->where('u = :u')
				->setParameter('u', $user)
			;
		}
		
		return $query;
	}
	
	public function findOneByUsernameOrEmail($username)
	{
		return $this
			->createQueryBuilder('u')
			->where('u.username = :username')
			->orWhere('u.email = :username')
			->setParameter('username', $username)
			->getQuery()
			->getOneOrNullResult()
		;
	}
}
