services:
    user.form.registration:
        class: UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: user_registration }
            
    user.form.profile:
        class: UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: user_profile }
            
    user.form.invitation_byTeam:
        class: UserBundle\Form\InvitationByTeamType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: user_invitation_by_team }
            
    user_oauth_aware.user_provider:
        class: UserBundle\Security\Provider
        arguments: ["@fos_user.user_manager",{google: googleId}]
        
    user.no_team_exception_listener:
        class: UserBundle\Exception\Listener\NoTeamExceptionListener
        arguments: [ "@router" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
         
    user.last_admin_exception_listener:
        class: UserBundle\Exception\Listener\LastAdminExceptionListener
        arguments: [ "@templating" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            
    user.check_team_listener:
        class: UserBundle\EventListener\CheckTeamListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            
    user.team_subscriber:
        class: UserBundle\EventSubscriber\TeamSubscriber
        arguments: [ "@app.archive", "@app.mailer", "@translator"]
        tags:
            - { name: kernel.event_subscriber }
            
    user.invitation_subscriber:
        class: UserBundle\EventSubscriber\InvitationSubscriber
        arguments: [ "@app.mailer", "@translator"]
        tags:
            - { name: kernel.event_subscriber }


