<?php

namespace CalendarBundle\Repository;
use UserBundle\Entity\User;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class EventRepository extends \Doctrine\ORM\EntityRepository
{
	abstract public function findByUserBetween(User $user, \DateTime $start, \DateTime $end);
	abstract public function findByUserNewerThan(User $user, \DateTime $start);
}
